// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace BlacksmithPress.Diabetes.Persistence.Database.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Measurements : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Measurements));
        
        string IMigrationMetadata.Id
        {
            get { return "201608281418227_Measurements"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
